# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      api:
        image: python:3.12
        ports:
          - 8000
        options: --name api

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up python
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.12

      # Install requirements
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Start FastAPI server
      - name: Start FastAPI server
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          uvicorn client_loan_prediction.app.main:app --host 0.0.0.0 --port 8000

      # Wait
      - name: Wait for FastAPI server to start
        run: |
          until curl http://127.0.0.1:8000/; do 
            echo "Waiting for FastAPI server to start ... "
            sleep 2
          done

      # Run the tests
      - name: Run tests
        run: |
          python -m unitest discover -s tests
      
