name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      api:
        image: python:3.9
        ports:
          - 8000:8000
        options: --name api

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r client_loan_approval/requirements.txt

    - name: Start FastAPI server
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/client_loan_approval
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &

    - name: Wait for FastAPI server to start
      run: |
        until curl http://127.0.0.1:8000/; do
          echo "Waiting for FastAPI server to start..."
          sleep 2
        done

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/client_loan_approval
        python -m unittest discover -s client_loan_approval/tests
